# development: &default
#   adapter: postgresql
#   database: copycopter_development
#   min_messages: WARNING

# test: &test
#   <<: *default
#   database: copycopter_test

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
